### ISSUE TITLE
Can't register my device

### ISSUE THREAD

**Issue by LucDV** [Gerenios/Authenticator#1]
after run command, I login with email and password. Login window change to My Sign-Ins and nothing happens next.
How I can fix it?
![Screenshot 2021-01-06 142628](https://user-images.githubusercontent.com/33018915/103741207-3b154e80-502b-11eb-98aa-224ec4265553.png)

**Comment by NestoriSyynimaa** [comment]
Were there any errors with `Register-AADIntMFAApp`? If not, that seems to be related to My Sign-Ins.
